// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" with { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/day1/1.tsx";
import * as $3 from "./routes/day1/2.tsx";
import * as $4 from "./routes/dayx/1.tsx";
import * as $5 from "./routes/dayx/2.tsx";
import * as $6 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/day1/1.tsx": $2,
    "./routes/day1/2.tsx": $3,
    "./routes/dayx/1.tsx": $4,
    "./routes/dayx/2.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
