// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $day1_1 from "./routes/day1/1.tsx";
import * as $day1_2 from "./routes/day1/2.tsx";
import * as $day2_1 from "./routes/day2/1.tsx";
import * as $day2_2 from "./routes/day2/2.tsx";
import * as $day3_1 from "./routes/day3/1.tsx";
import * as $day3_2 from "./routes/day3/2.tsx";
import * as $day4_1 from "./routes/day4/1.tsx";
import * as $day4_2 from "./routes/day4/2.tsx";
import * as $day5_1 from "./routes/day5/1.tsx";
import * as $day5_2 from "./routes/day5/2.tsx";
import * as $dayx_1 from "./routes/dayx/1.tsx";
import * as $dayx_2 from "./routes/dayx/2.tsx";
import * as $index from "./routes/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/day1/1.tsx": $day1_1,
    "./routes/day1/2.tsx": $day1_2,
    "./routes/day2/1.tsx": $day2_1,
    "./routes/day2/2.tsx": $day2_2,
    "./routes/day3/1.tsx": $day3_1,
    "./routes/day3/2.tsx": $day3_2,
    "./routes/day4/1.tsx": $day4_1,
    "./routes/day4/2.tsx": $day4_2,
    "./routes/day5/1.tsx": $day5_1,
    "./routes/day5/2.tsx": $day5_2,
    "./routes/dayx/1.tsx": $dayx_1,
    "./routes/dayx/2.tsx": $dayx_2,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
